repos:

# PRE-COMMIT
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: mixed-line-ending

# BLACK
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

# ISORT
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

# FLAKE8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8

# PYLINT
-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.4
    hooks:
        - id: pylint
          args:
            - --disable=unused-argument,missing-docstring

# MYPY
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
        - id: mypy
          additional_dependencies:
            - types-requests
          args:
            - --ignore-missing-imports
